### PR TITLE
Revive this Repository

### PR DESCRIPTION
**Pull request by mrclary**
Okay guys,
I've completed all the necessary updates to bring this project back to life.
There should be a companion PR in the Spyder repository: spyder-ide/spyder#12011.
These should address #2.

Of course, your comments/changes/recommendations are encouraged.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for this @mrclary!

I have one question: do you think we could create the new dmg in continuous infrastructure services?

**Comment by mrclary** [comment]
> Thanks a lot for this @mrclary!

You're welcome. I am happy to contribute. I've been using Spyder for many, many years now and we use it quite extensively on Macs at my company ([TAE Technologies](https://www.tae.com)), so I'm motivated to have a standalone Mac application.

> I have one question: do you think we could create the new dmg in continuous infrastructure services?

Well, I don't know anything about CI, but suppose we could.

**Comment by vancromy** [comment]
What's the status on this revival? Is this going to be merged into master? Would be nice to have a functioning standalone application for Macs. 

On a side note, I absolutely love Spyder. Keep up the great work guys.

**Comment by mrclary** [comment]
@vancromy , thanks for the compliment!

This is absolutely being revived. At present, I don't have permissions to merge the branch and I know that the core Spyder developers are very busy. In addition, I've had to make some changes to Spyder source code to accommodate the standalone app (spyder-ide/spyder#12011, spyder-ide/spyder#12232, spyder-ide/spyder#12235, spyder-ide/spyder#12236, spyder-ide/spyder#12237, spyder-ide/spyder#12271). These are not quite ready to merge.
While I can't say when these will be merged, and I can assure you that this revival will move forward.

After these initial pull requests are completed, I'll begin working on automated build deployments, so that users will not have to build the app themselves and just download it. But one thing at a time...

Thank you for being patient :-)

**Comment by CAM-Gerlach** [comment]
@ccordoba12 I imagine you'll have some comment on this :) ^

**Comment by ccordoba12** [comment]
Thanks @CAM-Gerlach for pinging me about this.

@vancromy, after seeing the great work @mrclary has done to revive this project and also noticing that about 60% (perhaps more) of our bug reports are related to installation/updating issues, we decided to (once again) distribute our own installers for macOS (and eventually Windows too).

So our plan is to release Spyder 4.1.4 at the beginning of June, then work with @mrclary to merge his PRs and start to distribute our installers along with 4.2.0, to be released (hopefully) in August.

**Comment by goanpeca** [comment]
@mrclary thanks for the continued effort in making this work! I have the PRs in the back of my bucket list and I will get to them at some point this week. Please be patient, and sorry for the delays in prividing more prompt feedback.

**Comment by mrclary** [comment]
Closing this PR in favor of spyder-ide/spyder#13992

**Pull request closed without merging**
